<h2>Login up using this form</h2>

<?php echo $this->tag->form("login/login"); ?>


<p>
    <label for="login">login</label>
    <?php echo $this->tag->textField([
        "login",
        "class" => "form-control",
        "placeholder" => "Enter login"
    ]); ?>
</p>

<p>
    <label for="password">password</label>
    <?php echo $this->tag->passwordField([
        "password",
        "class" => "form-control",
        "placeholder" => "Password"
    ]); ?>
</p>


<p>
    <?php echo $this->tag->submitButton([
        "Login",
        "class" => "btn btn-success"
    ]); ?>
</p>

</form>